### ISSUE TITLE
Reroute Dashboard Hub link

### ISSUE THREAD

**Issue by dumbcoder7** [eddiejaoude/eddiejaoude.github.com#108]
On the webpage, when I click on the link in red
![image](https://user-images.githubusercontent.com/43912470/100981582-0108e680-356d-11eb-8a94-84a60640064b.png)

I am directed to the twitter page of dashboardhub. Consider rerouting this link to `dashboardhub.io` directly, since that is what the user intends to take a look at. You can append the Twitter link to the end of the paragraph. 

Do you approve of this idea?

**Comment by eddiejaoude** [comment]
sure, thank you @dumbcoder7 👍

**Comment by dumbcoder7** [comment]
So...?
Should I create a pull request or will you be taking care of this later?

**Comment by eddiejaoude** [comment]
Feel free to create a PR if you like 🤓

**Comment by dumbcoder7** [comment]
Okay I will.
