### ISSUE TITLE
Double colon in the website's title.

### ISSUE THREAD

**Issue by Frakko** [eddiejaoude/eddiejaoude.github.com#109]
Current title:

- `Eddie Jaoude:: Senior Open Source Developer`

My suggestions:

- `Eddie Jaoude - Senior Open Source Developer`
- `Eddie Jaoude | Senior Open Source Developer`

**Comment by eddiejaoude** [comment]
Thank you 👍 - I thought the double colon looked good, but your examples are better 👍

**Comment by Frakko** [comment]
Thank you for your feedback! I could make a PR if you let me know which one you prefer 🙂

**Comment by eddiejaoude** [comment]
Awesome 👍 

I prefer the `|` 🤓 

Thank you!

**Comment by Frakko** [comment]
Done! 🥇
