### ISSUE TITLE
Redo website in ReactJS

### ISSUE THREAD

**Issue by eddiejaoude** [eddiejaoude/eddiejaoude.github.com#14]

**Comment by Azambadar** [comment]
Hi, please can you provide some more info that what sort of website you want to redo in reactJS?
Thanks

**Comment by eddiejaoude** [comment]
Good question. 

Similar information to what it has now, with a bit more. To have:

- Basic vanilla ReactJS site
- Using an open source Bootstrap or Material Design template
- Reading a `json` file for various information, like event lists etc

**Comment by eddiejaoude** [comment]
I kept it super simple for now
